### ISSUE TITLE
relative vs absolute paths

### ISSUE THREAD

**Issue by genmeblog** [scicloj/clay.el#6]
When given form or namespace is evaluated `clay-clean-buffer-file-name` returns absolute path which is used as `:source-path`  in `make!` call. If user sets `:base-source-path` it's concatenated making result not reachable.

When `:base-source-path` equals `clay` and buffer file name is `/home/user/anything/file.clj` then file `clay/home/user/anything/file.clj` is going to be rendered.

**Comment by daslu** [comment]
Fixed in versions 1.4, 1.5.
